name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Auto Versioning"]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Get latest tag
      id: get_version
      run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REMLA_TOKEN }}
    - name: Create secret file
      run: echo "${{ secrets.SECRET_FILE }}" > remla-team-12-2078257eb673.json
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/model-service:latest
          ghcr.io/${{ github.repository_owner }}/model-service:${{ env.VERSION }}

    - name: Verify pushed image
      run: echo "Image pushed!"
